apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app-container
        image: gcr.io/data-platform-347009/github.com/vivid-games/ci-cd
        ports: 
          - name: web
            containerPort: 5000

