apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app-container
        image: us-central1-docker.pkg.dev/data-platform-347009/data-platform-registry/ci-cd
        ports: 
          - name: web
            containerPort: 5000

