apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: heniosilva/ci-test
    argocd-image-updater.argoproj.io/myimage.update-strategy: digest
spec:
  project: default
  source:
    path: argocd-applications
    repoURL: https://github.com/chaosmisit/cd-ci.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
