apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: testapp=us-central1-docker.pkg.dev/machinelearning-325409/vg-ml-registry/ci-cd
    argocd-image-updater.argoproj.io/testapp.update-strategy: latest
    argocd-image-updater.argoproj.io/testapp.write-back-method: argocd
    argocd-image-updater.argoproj.io/testapp.force-update: "true"
spec:
  project: default
  source:
    path: application
    repoURL: https://github.com/chaosmisit/cd-ci.git
    targetRevision: HEAD
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
